// Lookup tables
export const CC_TABLE = {	
  "1": "One supercontinent",
  "2": "Two large continents",
  "3": "Three mid-sized continents",
  "4": "Fragmented archipelago",
  "5": "Crescent-shaped continent",
  "6": "Double-lobed continent",
  "7": "Tri-lobed continent",
  "8": "Chaotic / irregular",
  "9": "Single supercontinent",
  "A": "Dual continents",
  "B": "Fragmented continents",
  "C": "Island world",
  "D": "Ring-shaped landmass",
  "E": "Landmass with deep inland sea",
  "F": "Shattered archipelago",
  "G": "Continent with massive peninsula",
  "H": "Continent split by rift valley",
  "I": "Chaotic microcontinents",
  "J": "Continent with polar extension",
  "K": "Twin mirrored continents",
  "L": "Continent with central plateau",
  "M": "Submerged ancient continent",
  "N": "Continent with spiral coastline",
  "O": "Minor island chains",
  "P": "Deep inland seas",
  "Q": "Frequent rift valleys",
  "R": "High volcanic activity",
  "S": "Ancient eroded shields",
  "T": "Massive plateaus",
  "U": "Submerged land bridges",
  "V": "Fractured microcontinents",
  "W": "Extreme coastal cliffs",
  "X": "Dense archipelagos",
  "Y": "Chaotic terrain mixing",
  "Z": "Long east–west continent",
};


export const LM_TABLE = {
  "1": "Earth-like gradient",
  "2": "Hot world (expanded tropics)",
  "3": "Cold world (expanded tundra)",
  "4": "Asymmetric (one hemisphere hotter)",
  "5": "Patchy heat anomalies",
  "6": "Magical heat anomalies",
  "7": "Ice age world",
  "8": "Greenhouse world",
  "9": "Standard latitudinal gradient",
  "A": "Cold world",
  "B": "Hot world",
  "C": "Chaotic temperature flux",
  "D": "Equatorial cold band",
  "E": "Polar warm zones",
  "F": "Seasonally inverted temperatures",
  "G": "Localized magical heat pockets",
  "H": "Runaway desertification",
  "I": "Volcanic thermal belts",
  "J": "Ancient glacial scars",
  "K": "Planetwide monsoon engine",
  "L": "Hyper‑humid equator",
  "M": "Dry equator, wet poles",
  "N": "Seasonal extremes",
  "O": "Persistent heat domes",
  "P": "Glacial remnants",
  "Q": "Localized hot spots",
  "R": "Chaotic thermal pockets",
  "S": "Magical temperature flux",
  "T": "Permafrost creep",
  "U": "Runaway greenhouse pockets",
  "V": "GM’s choice",
};

export const WE_TABLE = {
  "1": "West → East (Earth-like)",
  "2": "East → West",
  "3": "North → South",
  "4": "South → North",
  "5": "Monsoon-dominated",
  "6": "Chaotic / magical",
  "7": "Standard trade winds",
  "8": "Strong monsoon cycle",
  "9": "Chaotic / magical winds",
  "A": "Dry continental winds",
  "B": "Moist oceanic winds",
  "C": "Jet stream instability",
  "D": "Storm‑breeding equator",
  "E": "Polar cyclone engine",
  "F": "Seasonally reversing winds",
  "G": "Dust‑laden global currents",
  "H": "Hyper‑storm convergence zones",
  "I": "Permanent hurricane belt",
  "J": "High‑altitude wind rivers",
  "K": "Arcane wind anomalies",
  "L": "Planetwide fog cycles",
  "M": "Dry lightning regions",
  "N": "Reverse seasonal winds",
  "O": "Polar vortex surges",
  "P": "Equatorial oscillations",
  "Q": "Hyper‑monsoon cycles",
  "R": "Magical wind anomalies",
  "S": "Dust‑laden currents",
  "T": "Storm‑breeding zones",
  "U": "GM’s choice",
};

export const TR_TABLE = {
    "1": "Flat world",
    "2": "One major mountain range",
    "3": "Two parallel ranges",
    "4": "Coastal range",
    "5": "Inland arc",
    "6": "Rift valley",
    "7": "Volcanic arc",
    "8": "Plateau world",
    "9": "Fragmented highlands",
    "A": "Hyper-mountainous",
    "B": "Subduction-dominated",
    "C": "Multiple mountain ranges",
    "D": "Rift valley system",
    "E": "Volcanic arcs",
    "F": "High plateaus",
    "G": "Low, eroded terrain",
    "H": "Active subduction zones",
    "I": "Crustal thinning",
    "J": "Deep chasms",
    "K": "Dormant supervolcano",
    "L": "Chaotic tectonics",
    "M": "Massive shield continent",
    "N": "Hyper‑active volcanic belts",
    "O": "Ancient uplift scars",
    "P": "Planetwide fault network",
    "Q": "Floating or fractured crust",
    "R": "Hidden fault lines",
    "S": "Subducted microplates",
    "T": "Active magma plumes",
    "U": "Frequent tremors",
    "V": "High geothermal activity",
    "W": "Titanic mountain roots",
    "X": "Hyper‑active subduction",
    "Y": "GM’s choice",
};

export const HY_TABLE = {
  "1": "Sparse rivers",
  "2": "One major river",
  "3": "Two major rivers",
  "4": "River lattice",
  "5": "Lake chains",
  "6": "Wetland basins",
  "7": "Arid basins",
  "8": "Seasonal floods",
  "9": "Wetland belts",
  "A": "Glacial meltwater",
  "B": "Coastal deltas",
  "C": "Karst aquifers",
  "D": "Monsoon rivers",
  "E": "Tectonic basins",
  "F": "Ancient inland seas",
  "G": "Chaotic hydrology",
  "H": "Subterranean river networks",
  "I": "Massive endorheic basins",
  "J": "Hyper‑saline lakes",
  "K": "Intermittent ghost rivers",
  "L": "Volcanic steam‑fed springs",
  "N": "Seasonal flash floods",
  "O": "Braided river systems",
  "P": "Ancient dried riverbeds",
  "Q": "Subterranean aquifers",
  "R": "Mineral‑rich waters",
  "S": "Magical springs",
  "T": "Saltwater intrusion",
  "M": "Toxic wetlands",
  "U": "GM’s choice",
};

export const SF_TABLE = {
  "1": "None",
  "2": "Volcanic province",
  "3": "Rift valley",
  "4": "Ancient crater",
  "5": "Inland sea",
  "6": "Salt flats",
  "7": "Massive canyon",
  "8": "Great swamp",
  "9": "Coral archipelago",
  "A": "Ice shelf",
  "B": "Magical anomaly",
  "C": "GM’s choice",
};
